### ISSUE TITLE
[ENHANCEMENT] weapon choice for new players is a mess

### ISSUE THREAD

**Issue by mayersgamer** [KitsuneLab-Development/K4-Arenas#12]
weapons needs to be the same between players 

exp for pistol rounds : deagle vs deagle or usp vs usp

and when the rifle round or sniper or smg is on , there should not be a secondary by default.

players are confused by what weapon the enemy is using , the only option for players that should use is if they want knife or scout rounds .

this options should be by default.

**Comment by K4ryuu** [comment]
You can freely manage the weapons of any rounds in the cfg. You can delete, create modify and round. Feel free to use the settings. :)

**Comment by mayersgamer** [comment]
> You can freely manage the weapons of any rounds in the cfg. You can delete, create modify and round. Feel free to use the settings. :)

{
      "TranslationName": "k4.rounds.awp",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_awp",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },

i want here only awp no pistol is this correct ?

**Comment by mayersgamer** [comment]
looks i have disabled by default the knife rounds 
disabled itt in the game 
removed it from the config , but still knife rounds is playing 


// This configuration was automatically generated by CounterStrikeSharp for plugin 'K4-Arenas', at 2024/05/04 08:08:30
{
  "use-predefined-config": true,
  "database-settings": {
    "host": "gameslim23.bisecthosting.com",
    "username": "u94664_VMm0JSS7KC",
    "database": "s94664_arena",
    "password": "=Ex8PRJHP^aVEBu9Wp^=nAG9",
    "port": 3306,
    "sslmode": "none",
    "table-prefix": "",
    "table-purge-days": 30
  },
  "command-settings": {
    "gun-pref-commands": [
      "guns",
      "gunpref",
      "weaponpref"
    ],
    "round-pref-commands": [
      "rounds",
      "roundpref"
    ],
    "queue-commands": [
      "queue"
    ],
    "afk-commands": [
      "afk"
    ],
    "challenge-commands": [
      "rasaras",
      "duel"
    ],
    "challenge-accept-commands": [
      "yes",
      "capprove"
    ],
    "challenge-decline-commands": [
      "cdecline",
      "cdeny"
    ]
  },
  "round-settings": [
    {
      "TranslationName": "k4.rounds.m4a1S",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_m4a1",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.ak47",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ak47",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.scout",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ssg08",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.awp",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_awp",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.deagle",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_deagle",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.2vs2",
      "TeamSize": 2,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.3vs3",
      "TeamSize": 3,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    }
  ],
  "compatibility-settings": {
    "metamod-skinchanger-compatibility": false,
    "force-arena-clantags": false
  },
  "default-weapon-settings": {
    "default-rifle": null,
    "default-sniper": null,
    "default-smg": null,
    "default-lmg": null,
    "default-shotgun": null,
    "default-pistol": null
  },
  "ConfigVersion": 1
