### ISSUE TITLE
[BUG] knife keeps coming

### ISSUE THREAD

**Issue by mayersgamer** [KitsuneLab-Development/K4-Arenas#13]
- knife keeps coming even tho i disabled it first then removed it from config.
- weapon that i have set enabled by default are all disabled once were in game.

// This configuration was automatically generated by CounterStrikeSharp for plugin 'K4-Arenas', at 2024/05/04 08:08:30
{
  "use-predefined-config": true,
  "database-settings": {
    "host": "",
    "username": "",
    "database": "",
    "password": "",
    "port": 3306,
    "sslmode": "none",
    "table-prefix": "",
    "table-purge-days": 30
  },
  "command-settings": {
    "gun-pref-commands": [
      "guns",
      "gunpref",
      "weaponpref"
    ],
    "round-pref-commands": [
      "rounds",
      "roundpref"
    ],
    "queue-commands": [
      "queue"
    ],
    "afk-commands": [
      "afk"
    ],
    "challenge-commands": [
      "rasaras",
      "duel"
    ],
    "challenge-accept-commands": [
      "yes",
      "capprove"
    ],
    "challenge-decline-commands": [
      "cdecline",
      "cdeny"
    ]
  },
  "round-settings": [
    {
      "TranslationName": "k4.rounds.m4a1S",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_m4a1",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.m4a4",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_m4a4",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.ak47",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ak47",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.famas",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_famas",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.galil",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_galilar",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.mac10",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_mac10",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.UMP45",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ump45",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.scout",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ssg08",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.awp",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_awp",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.usp",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_usp_silencer",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.deagle",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_deagle",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.tec9",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_tec9",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.Revolver",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_revolver",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.2vs2",
      "TeamSize": 2,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.3vs3",
      "TeamSize": 3,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    }
  ],
  "compatibility-settings": {
    "metamod-skinchanger-compatibility": false,
    "force-arena-clantags": false
  },
  "default-weapon-settings": {
    "default-rifle": null,
    "default-sniper": null,
    "default-smg": null,
    "default-lmg": null,
    "default-shotgun": null,
    "default-pistol": null
  },
  "ConfigVersion": 1
}

**Comment by K4ryuu** [comment]
Delete your SQL details, cuz people gonna login :D

1. Knife is always given.
2. Default weapons applied to new player only. Who already played on the server you don't change their prefs with it.

**Comment by mayersgamer** [comment]
ok so i need to delete database everytime i update ok 

and will let you know

**Comment by K4ryuu** [comment]
> ok so i need to delete database everytime i update ok
> 
> and will let you know

Yes, if you update default preferences you have to delete the database.
But delete this what you shared here cuz you leaked all your MySQL credentials......

**Comment by mayersgamer** [comment]
> > ok so i need to delete database everytime i update ok
> > and will let you know
> 
> Yes, if you update default preferences you have to delete the database. But delete this what you shared here cuz you leaked all your MySQL credentials......

is there a command to reset data for all players ?

**Comment by K4ryuu** [comment]
Sadly no
