### ISSUE TITLE
[BUG] knife round keeps coming

### ISSUE THREAD

**Issue by mayersgamer** [KitsuneLab-Development/K4-Arenas#14]
- New database first time use 
- tested with 2 players
- default config knife disabled , both players have knife round disabled per default while in server.
result testing = knife round keeps popping

// This configuration was automatically generated by CounterStrikeSharp for plugin 'K4-Arenas', at 2024/05/06 07:12:27
{
  "use-predefined-config": true,
  "database-settings": {
    "host": "tatatat",
    "username": "aaaaa",
    "database": "atatat",
    "password": "0at",
    "port": 3305,
    "sslmode": "none",
    "table-prefix": "",
    "table-purge-days": 30
  },
  "command-settings": {
    "gun-pref-commands": [
      "guns",
      "gunpref",
      "weaponpref"
    ],
    "round-pref-commands": [
      "rounds",
      "roundpref"
    ],
    "queue-commands": [
      "queue"
    ],
    "afk-commands": [
      "afk"
    ],
    "challenge-commands": [
      "challenge",
      "duel"
    ],
    "challenge-accept-commands": [
      "accept",
      "yes"
    ],
    "challenge-decline-commands": [
      "cdecline",
      "cdeny"
    ]
  },
  "round-settings": [
    {
      "TranslationName": "k4.rounds.rifle",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 0,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.sniper",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 1,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.shotgun",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 4,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.pistol",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.smg",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 2,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.lmg",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 3,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.m4a1S",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_m4a1",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.m4a4",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_m4a4",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.ak47",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ak47",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.famas",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_famas",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.galil",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_galilar",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.mac10",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_mac10",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.UMP45",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ump45",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.scout",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ssg08",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.awp",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_awp",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.usp",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_usp_silencer",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.deagle",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_deagle",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.tec9",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_tec9",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.Revolver",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_revolver",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.p250",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_p250",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.2vs2",
      "TeamSize": 2,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.3vs3",
      "TeamSize": 3,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.knife",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": false
    }
  ],
  "compatibility-settings": {
    "metamod-skinchanger-compatibility": false,
    "force-arena-clantags": false
  },
  "default-weapon-settings": {
    "default-rifle": null,
    "default-sniper": null,
    "default-smg": null,
    "default-lmg": null,
    "default-shotgun": null,
    "default-pistol": null
  },
  "ConfigVersion": 1
}

**Comment by K4ryuu** [comment]
You cannot disable knife. Why you think you can? I just told you in the latest issue of yours that it always given.

**Comment by mayersgamer** [comment]
> You cannot disable knife. Why you think you can? I just told you in the latest issue of yours that it always given.

so knife round is obligatory ?  i hope you understand me , knife round is fighting with knife without any other weapon.

**Comment by K4ryuu** [comment]
A new setting has been added to the upcoming release to disable knife by default.
