### ISSUE TITLE
[REMINDER] Arena's sort by Damage

### ISSUE THREAD

**Issue by MaCoRko** [KitsuneLab-Development/K4-Arenas#15]
Hello,

K4ryuu and I had discussion about arena sorting by damage and he asked me to open a Issue on GitHub to say that, so here am I, i asked about Arena sorts by Damage and he said to me that is still not available but will be in future and to open a issue as a reminder, so here am I. I wish to see more from this and all of your projects in future, thank you :D

**Comment by K4ryuu** [comment]
The fix has been added to the upcoming release. Thank you!
