### ISSUE TITLE
[CRASH] Error

### ISSUE THREAD

**Issue by brkvlr** [KitsuneLab-Development/K4-Arenas#16]
[39;49m[37m07:15:06[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m
[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m
[39;49m[37m ---> System.InvalidOperationException: Sequence contains no elements[39;49m
[39;49m[37m   at System.Linq.ThrowHelper.ThrowNoElementsException()[39;49m
[39;49m[37m   at System.Linq.Enumerable.MinFloat[T](IEnumerable`1 source)[39;49m
[39;49m[37m   at ArenaFinder..ctor()[39;49m
[39;49m[37m   at Arenas..ctor(Plugin plugin)[39;49m
[39;49m[37m   at K4Arenas.Plugin.<Initialize_Events>b__51_6(EventRoundPrestart event, GameEventInfo info)[39;49m
[39;49m[37m   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)[39;49m
[39;49m[37m   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)[39;49m
[39;49m[37m   --- End of inner exception stack trace ---[39;49m
[39;49m[37m   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)[39;49m
[39;49m[37m   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m
[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100[39;49m

**Comment by K4ryuu** [comment]
Greetings, 
Do you have some context about the crash? When it happens or so? Could be useful :D

**Comment by brkvlr** [comment]
I didn't pay attention, I will write if I find anything.

**Comment by brkvlr** [comment]
Addition: They said it happened when the map changed

**Comment by brkvlr** [comment]
Today is the 5th crash, it crashes a lot, can you solve it? @K4ryuu

**Comment by K4ryuu** [comment]
The plugin has now a feature to detect map that has no spawns at all and going to stop searching for arenas then. You gonna see in the logs if a map has no "info_player_counterterrorist" and "info_player_terrorist". I advise to remove those maps, cuz no people can be spawned.
