### ISSUE TITLE
[BUG] Armor

### ISSUE THREAD

**Issue by brkvlr** [KitsuneLab-Development/K4-Arenas#17]
Doesn't give armor in pistol rounds, even though it's set.

**Comment by K4ryuu** [comment]
Check that if you have **mp_free_armor** and **mp_equipment_reset_rounds** in any other value which is not 0.

**Comment by brkvlr** [comment]
mp_free_armor 0 
mp_equipment_reset_rounds 0

**Comment by brkvlr** [comment]
{
      "TranslationName": "k4.rounds.pistol",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": false
    },

**Comment by K4ryuu** [comment]
I tested this issue, but I was unable to reproduce it on my dev server
