### ISSUE TITLE
[FEATURE] Built in Anti-AFK system

### ISSUE THREAD

**Issue by hApYeNd1337** [KitsuneLab-Development/K4-Arenas#19]
it would be nice to add an AFK system when it stays for more than X seconds so that the afk is automatically moved to the viewer because the existing ones do not work with the arena mode

**Comment by K4ryuu** [comment]
In the upcoming release external anti-afk plugins can call Arena's AFK actions. This provides a proper support to any external plugin that wants to handle AFK players.
