### ISSUE TITLE
[FEATURE] Multilingualization.

### ISSUE THREAD

**Issue by norbee16** [KitsuneLab-Development/K4-Arenas#21]
I would recommend it, of course if it can be solved.

To make this mode multilingual. As were most of the plugins in csgo. Looking at the game language of the given player (or if it can be solved in another way), but so that only one specific language can be used on the server.

**Comment by K4ryuu** [comment]
You can solve this by using a geo location based language setter and a lang selector menu. The plugin is using CSS standards for the translations.
