### ISSUE TITLE
[BUG] Specator

### ISSUE THREAD

**Issue by hApYeNd1337** [KitsuneLab-Development/K4-Arenas#22]
when I write !afk it puts me on the viewer and lets me kill the players and they don't see me.. as if I were alive. 
![20240602230318_1](https://github.com/K4ryuu/K4-Arenas/assets/106784898/f7e0bbd0-ca51-4db8-b1bb-c7468053bb62)

**Comment by Cruze03** [comment]
Can you please explain more? Also:
1) When did you type !afk? After the round start? After the round end? or how much time after the round start did you type?
2) Did you recently connect when you typed !afk?
3) Is this a rare occurrence or happen every time?

**Comment by Siudzix** [comment]
Not the same. Im not invisible to other players on specific arena.

**Comment by Siudzix** [comment]
ah.. I forgot that You are far behind our fixes...

**Comment by K4ryuu** [comment]
I close the issue, due to no further information provided.
