### ISSUE TITLE
[BUG] Round Restart

### ISSUE THREAD

**Issue by craivyx** [KitsuneLab-Development/K4-Arenas#23]
When both teams are alive, it doesn't end the round even if all arenas are finished.

- CSS Version: v247
- Plugin Version 1.4.4 (release)

![image](https://github.com/user-attachments/assets/b651c763-e96c-47a5-b7e5-e211472e2af3)

**Comment by craivyx** [comment]
![image](https://github.com/user-attachments/assets/aef32896-56fd-417b-ad59-5423fdac3ed4)
Tested with more players and still

**Comment by K4ryuu** [comment]
The round termination methods has changed in the upcoming release to support both bots and players a bit better.
