### ISSUE TITLE
[BUG] Warmup bug

### ISSUE THREAD

**Issue by Binev96** [KitsuneLab-Development/K4-Arenas#24]
**Describe the bug**
I've found that there is warmup that never ends.

**To Reproduce**
I've start the server and never join in it, but after few hours I've found that players are unable to move.

**Logs/Screenshots**
I've restart the server to check will this thing continue, but it was gone, next time I will make a video.

**Environment (please complete the following information):**
- OS: Linux
- CSS v247
- Plugin Version: v1.4.4 (Latest)
- Configs: below 
```
// Changing these might break the gamemode
bot_quota 0
mp_autoteambalance 0
mp_ct_default_primary ""
mp_ct_default_secondary ""
mp_t_default_primary ""
mp_t_default_secondary ""
mp_halftime 0
mp_join_grace_time 0
mp_match_can_clinch 0
mp_respawn_immunitytime 0

// Essential for better player experience
mp_autokick 0
mp_warmuptime 0
mp_maxmoney 0
mp_teamcashawards 0
mp_playercashawards 0
sv_disable_radar 1
sv_ignoregrenaderadio 1

// You can change whatever you want here, up to your preferences
mp_freezetime 0
mp_forcecamera 0
mp_endmatch_votenextmap 0
mp_match_end_changelevel 1
mp_match_end_restart 0
mp_maxrounds 0
mp_round_restart_delay 2
sv_allow_votes 0
mp_timelimit 8
mp_win_panel_display_time 5
sv_talk_enemy_dead 1
sv_talk_enemy_living 1
sv_deadtalk 1

```
**Additional context**
Here are the other plugins that I've used
RockTheVote
K4-System
Advertisment
AdminList (should be removed due to K4-System has !admins, good job)

P.S.
More information tomorrow I will leave server on, to try replicate the bug.

**Comment by Binev96** [comment]
So, I've find out how it happens, also I've replicated it twice without RockTheVote plugin to be sure its not the cause.

1. Server is empty
2. Player came into the server timeleft starts count
3. Player leave before timeleft ends
4. Player joins the server after timeleft its ended, and the last round is over
5. Match Cancelled is displayed (that one from cs2), map do not change or reset (Even if I vote)
6. Players left because its stuck
6.1. Another player joins, it is spawned with weapons (random weapons I guess), and he cannot move with (W A S D) and even cannot move mouse (to aim)


If the player stays in the server while last round with "No Time Limit" msg everything is fine.
But if noone is there and joins after last round, its stucked
I've tried with multiple reconnects but without effect

P.S. Additional I've got WARMUP tag

Contact me here for further info or questions.

Awesome job with plugin!

**Comment by K4ryuu** [comment]
I've checked the warmup issue, which most probably was caused by some warmup timing issue (which also happens when using that flashfixhint stuff), so I added it to my server and tested it. The incompatibility has been fixed for sure with a restart on invalid warmup data found. Feel free to open an issue if you still experience the issue as I'm back on track with Arenas aswell.
