### ISSUE TITLE
[HELP] MySQL database not connecting

### ISSUE THREAD

**Issue by axeldread** [KitsuneLab-Development/K4-Arenas#25]
1. Summary:
Problem Description: Plugin not connecting to MySQL database even though it is configured and running.
Date and Time of Occurrence: Today around 8AM Central time (UTC -6)
2. Detailed Description:
Steps to Reproduce:

Start Server
Get error [EROR] plugin:K4-Arenas Please setup your MySQL database
Expected Result: Plugin to connect to configured MySQL database
Actual Result: Plugin doesnt connect.
3. Technical Details:
Hosting Plan: Linux Debian 12 VDS
Error Messages: [EROR] plugin:K4-Arenas Please setup your MySQL database
4. Troubleshooting Steps Taken:
Reconfigured database, tested on other applications, reinstalled plugin multiple times.

My MySQL server is running, and i have filled the config as follows: 
`  "use-predefined-config": true,
  "database-settings": {
    "host": "localhost",
    "username": "e1",
    "database": "e1_1v1",
    "password": "xxxxx",
    "port": 3306,
    "sslmode": "none",
    "table-prefix": "1v1_",
    "table-purge-days": 30
  },`

**Comment by axeldread** [comment]
I am sorry for bad post. this is my first time using github

**Comment by axeldread** [comment]
This is the entirety of my configuration file. PLease note any errors i've made.
`// This configuration was automatically generated by CounterStrikeSharp for plugin 'K4-Arenas', at 2024/08/05 02:00:47
{
  "use-predefined-config": true,
  "database-settings": {
    "host": "localhost",
    "username": "e1",
    "database": "e1_1v1",
    "password": "xxxxxxx",
    "port": 3306,
    "sslmode": "none",
    "table-prefix": "1v1_",
    "table-purge-days": 30
  },
  "command-settings": {
    "gun-pref-commands": [
      "guns",
      "gunpref",
      "weaponpref"
    ],
    "round-pref-commands": [
      "rounds",
      "roundpref"
    ],
    "queue-commands": [
      "queue"
    ],
    "afk-commands": [
      "afk"
    ],
    "challenge-commands": [
      "challenge",
      "duel"
    ],
    "challenge-accept-commands": [
      "caccept",
      "capprove"
    ],
    "challenge-decline-commands": [
      "cdecline",
      "cdeny"
    ]
  },
  "round-settings": [
    {
      "TranslationName": "k4.rounds.rifle",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ak47",
      "SecondaryWeapon": "weapon_deagle",
      "UsePreferredPrimary": true,
      "PrimaryPreference": 0,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.rifle",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_m4a1_silencer",
      "SecondaryWeapon": "weapon_deagle",
      "UsePreferredPrimary": true,
      "PrimaryPreference": 0,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.rifle",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_m4a1",
      "SecondaryWeapon": "weapon_deagle",
      "UsePreferredPrimary": true,
      "PrimaryPreference": 0,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.pistol",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_fiveseven",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.scout",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_ssg08",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.awp",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_awp",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.deagle",
      "TeamSize": 1,
      "PrimaryWeapon": null,
      "SecondaryWeapon": "weapon_deagle",
      "UsePreferredPrimary": false,
      "PrimaryPreference": null,
      "UsePreferredSecondary": false,
      "Armor": false,
      "Helmet": false,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.smg",
      "TeamSize": 1,
      "PrimaryWeapon": "weapon_mp9",
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 2,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": true
    },
    {
      "TranslationName": "k4.rounds.2vs2",
      "TeamSize": 2,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
    {
      "TranslationName": "k4.rounds.3vs3",
      "TeamSize": 3,
      "PrimaryWeapon": null,
      "SecondaryWeapon": null,
      "UsePreferredPrimary": true,
      "PrimaryPreference": 6,
      "UsePreferredSecondary": true,
      "Armor": true,
      "Helmet": true,
      "EnabledByDefault": false
    },
  ],
  "compatibility-settings": {
    "metamod-skinchanger-compatibility": false,
    "force-arena-clantags": false,
    "block-flash-of-not-opponent": false,
    "block-damage-of-not-opponent": false,
    "give-knife-by-default": false
  },
  "default-weapon-settings": {
    "default-rifle": null,
    "default-sniper": null,
    "default-smg": null,
    "default-lmg": null,
    "default-shotgun": null,
    "default-pistol": null
  },
  "arena-math-overrides": 0,
  "ConfigVersion": 4
}`

**Comment by K4ryuu** [comment]
Greetings,
The `[EROR] plugin:K4-Arenas Please setup your MySQL database` message is visible when you have all the config values for database on default settings.
