### ISSUE TITLE
[BUG] Spectator bug

### ISSUE THREAD

**Issue by Siudzix** [KitsuneLab-Development/K4-Arenas#26]
**Describe the bug**
A player on a Spectator is thrown into an arena for a challenge, after which he is not put into a spectator but into random arenas as 3rd player with WAITING status. 

**To Reproduce**
In one round type !afk and then challenge other player, he have to accept duel before round ends. 

**Expected behavior**
Immediately change status of player to AFK; after finished challenge, player who was afk/spectator is thrown back into Spectator.

**Comment by K4ryuu** [comment]
Duplicate of #22 which I stated we check after weekend.
