### ISSUE TITLE
Unable to use commands

### ISSUE THREAD

**Issue by zyhsck** [KitsuneLab-Development/K4-Arenas#29]
I typed .guns,/guns,!guns in the cs2 player chat bar and couldn't trigger the weapon settings, same with other commands such as rounds, can you give a tutorial on how to use it, preferably a video one, thanks!

**Comment by K4ryuu** [comment]
Set your menu type to your preferred one (chat or center).
Also update your plugin to 1.5.1 if you are using center menu.

Then you can just use the commands as any other CSS command on your server.
