### ISSUE TITLE
[ENHANCEMENT] Changes

### ISSUE THREAD

**Issue by brkvlr** [KitsuneLab-Development/K4-Arenas#3]
1) Afk message: Sends text to chat 3 times, should be reduced to 1.
2) The frequency of !rounds and !afk messages should be reduced.
3) A special line should be added for the "No opponent" message to improve the translation.
       > You are in arena 1 against No opponent and playing x round.
       + You have no opponent.
4) I use Weaponpaints, our knife skins are broken. I use the configuration as follows. What is the solution?
  "compatibility-settings": {
    "metamod-skinchanger-compatibility": false,
    "css-skinchanger-knife-compatibility": true
  },

**Comment by K4ryuu** [comment]
Greetings,
1. Will be reduced in the next update.
2. Could you describe it a bit better? (I'm going to add center menus tho)
3. The line pretty much says no opponent, so why to print it again?
4. What is "broken" means?

**Comment by brkvlr** [comment]
2) The !afk and !rounds messages appearing in the chat at the beginning of each round are distracting. We cannot easily see who the opponent is.
3) What I meant by a different line was to say that a different message should appear in cases where there is no opponent. Writing "no opponent" is enough, writing round type and arena is unnecessary, for example.
4) My Weaponpaints selected weapon is visible on the right, but in knife rounds I get the skinless version.

**Comment by brkvlr** [comment]
4) Note: When I went back to the old version, the knife got better.

**Comment by K4ryuu** [comment]
Most of the requested changes have been made and going to be published within 1.3.5.
Thank you
