### ISSUE TITLE
[ENHANCEMENT] Update player preferences

### ISSUE THREAD

**Issue by Letaryat** [KitsuneLab-Development/K4-Arenas#5]
**Describe the enhancement**
Update query that changes preferences such as weapons and round to be executed when players selected his preferences. 

**Problem and motivation**
In 1.3.7 and 1.3.6 versions of the plugin, queries are updated on player disconnect. That creates a small problem in which preferences doesn't save on map change and it resets to the default or previous values.

**Suggested solution**
Update query should be runned when players selects his preferred weapon or round. 

**Alternatives**
-

**Additional context**
-

**Comment by K4ryuu** [comment]
Greetings,
It won't be changed to save instantly, because it is not good for performance. The problem (with more other) got already fixed, and will be published Today. 

Best Regards,
K4ryuu
