### ISSUE TITLE
Arena + roundendsounds

### ISSUE THREAD

**Issue by Prull99** [KitsuneLab-Development/K4-Arenas#6]
Hey. Im using roundendsounds with this plugin and when a player join to the server after end of the round then 2 songs start to play. Also when someone get killed after end of the round. Can you please check it if you can do something about it? On my other servers I dont have this problem.

**Comment by K4ryuu** [comment]
The request has no relation for the plugin. This plugin is just the base of the gamemode, so plugins like that should be as external addons. Not everyone wants to use things like that.

**Comment by K4ryuu** [comment]
I missunderstood your issue. Could you detail your problem? Without further information or valid report I cant do much against it.

**Comment by Prull99** [comment]
When I use the arena plugin with the roundendsound I have that bug that the roundendsound plays 2 music at the same time.
1. When a player joins to the server at the end of the current round.
2. When someone gets killed after the round ends.
These 2 actions somehow trigger the roundendsounds plugin to play music 1 more time. (The server doesnt give error about that.)

**Comment by toorisrael** [comment]
Rounds keep restarting / ending multiple times if someone gets killed after round end or just joins server. Also round restart dealy is not respected sometimes (match is restarting?).

**Comment by K4ryuu** [comment]
Gonna check on it within the upcoming days

**Comment by toorisrael** [comment]
This change should respect round restart delay and also it would be better to always have winning team, so it could be random. This won't however fix multiple round ends in one round. I think TerminateRound happens multiple times (one time by real round time limit and another reasons by plugin) but I need to dig in the code a little more.
```c
Server.NextFrame(() =>
{
				//gameRules.TerminateRound(3, tCount > ctCount ? RoundEndReason.TerroristsWin : ctCount > tCount ? RoundEndReason.CTsWin : RoundEndReason.RoundDraw);
				int roundrestartdelay = 3;
    var convar = ConVar.Find("mp_round_restart_delay");
				if (convar != null)
				{
        roundrestartdelay = convar.GetPrimitiveValue<int>();
    }
    gameRules.TerminateRound(roundrestartdelay, (RoundEndReason)rng.Next(8, 9));
});
```
** untested, and I'm new to C#
EDIT: I've used roundterminated bool in round_start, round_end and TerminateRoundIfPossible to mark and check if round already has been terminated.

**Comment by K4ryuu** [comment]
Patched hopefully in the upcoming release. Please re-open this issue, if you see any problem with it. 
Thank you!
