### ISSUE TITLE
[FEATURE] GiveNamedItem by virtual function of ItemServices

### ISSUE THREAD

**Issue by toorisrael** [KitsuneLab-Development/K4-Arenas#8]
Using virtual function offset to give player weapons will add support for any skin plugin and won't break any metamod source plugin compatibility which needs to use GiveNameItem2 sig.

https://github.com/Source2ZE/CS2Fixes/blob/main/src/cs2_sdk/entity/services.h#L166

**Comment by K4ryuu** [comment]
I think you are lost a little bit, because GiveNamedItem calls VirtualFunction. It is pretty much a wrapper around it to use it safer.

You find it here: https://github.com/roflmuffin/CounterStrikeSharp/blob/main/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs#L17C5-L27C6

**Comment by toorisrael** [comment]
The problem with cssharp core is it's not using virtual function for GiveNamedItem. It calls it by address (signature).
So for example I can't detour GiveNamedItem in metamod, because css won't load. Than I have to detour GiveNamedItem2 in my metamod plugin, which is called before GiveNamedItem. If I setup skins on GiveNamedItem2, they will never work if weapon given by css core GiveNamedItem.

Edit: I asked cssharp author to add it, and I guess it will be added soon, so nvm
https://github.com/roflmuffin/CounterStrikeSharp/pull/427/files
