### ISSUE TITLE
[BUG] Post duel bug

### ISSUE THREAD

**Issue by msk-01** [KitsuneLab-Development/K4-Arenas#9]
**Describe the bug**
After finishing a duel, the players that were in a duel get spawned in the same arena as another two players (and can get spawned inside an enemy). In the scoreboard, the players still have the "CHALLENGE" tag. Their preferences (weapons, rounds) get reset to defaults. Produces no error in the console.  

**To Reproduce**
Happens every time someone enters a duel on my server.

**Logs/Screenshots**
I can make a video if needed.

**Environment (please complete the following information):**

- OS: Ubuntu
- CSS Version: 228
- Plugin Version: 1.3.10
- Configs (i can provide if needed)

**Comment by K4ryuu** [comment]
The problem has been solved with one additional changes in the latest release. Thank you for the report!
